version: '3'

services:
    neo4j:
        image: neo4j
        networks:
            - host
        ports:
            - 7474:7474
            - 7687:7687
        environment:
            - NEO4J_AUTH=neo4j/zeppelin
    zeppelin:
      build: ./zeppelin
      image: zeppelin
      container_name: zeppelin
   
      ports:
        - "18080:8080"
networks:
    host: